# server {
#     listen 80;
#     server_name localhost;
    ##PHP（Laravel想定）の public 配信
#     root /var/www/html/public;

#     index index.php index.html;

#     location / {
        ##ファイルなければ 全部 index.php に投げる、Laravel のルーティング前提
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
        ##PHP-FPM（app コンテナ）と連携する設定
#         fastcgi_pass app:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }
# }

server {
    #nginx が **80番ポート**で待ち受けdocker-compose で `8080:80` にしてるからブラウザは `http://localhost:8080`
  listen 80;

  root /var/www/frontend/public;
  #`/` に来たら`index.html` を返す
  index index.html;

  location / {
    #指定されたファイルがあれば返す、なければディレクトリ探す、それでもなければ 404
    try_files $uri $uri/ =404;
  }
}
